### ISSUE TITLE
Returns "Invariant does not exists"

### ISSUE THREAD

**Issue by trivedi-nitesh** [ericpony/polynomial-loop-invariant-synthesis#2]
Works well for random-walk but returns "Invariant does not exists" for others(Ex: binomial). 
Below is the tail of output generated in my case(with verbose= 100):
LCM: 30
Token (JSified): 30*((3/5)*(1)+(-3/5)*Math.pow(1,2)+(1/5)*(0)*(1)+(-3/10)*(2)+(3/10)*Math.pow(2,2))
Token (JSified): 30*((-1/5)*(1)+(6/5)*Math.pow(1,2)+(-2/5)*(0)*(1)+(-2/5)*(2)+-1*(2)*(1)+(2/5)*Math.pow(2,2))
Token (JSified): 30*((-12/5)*(1)+(12/5)*Math.pow(1,2)+(-3/10)*(0)*(1)+(6/5)*(2)+(-3/2)*(2)*(1)+(-1/2)*(2)*(0)+(3/10)*Math.pow(2,2))
Token (JSified): 30*((13/10)*(1)+(-13/10)*Math.pow(1,2)+(1/10)*(0)*(1)+(-2/5)*(2)+(1/2)*(2)*(1)+(1/2)*(2)*(0)+(-1/10)*Math.pow(2,2))
Token (JSified): 30*(3+(6/5)*(1)+(-21/5)*Math.pow(1,2)+(-5/2)*(0)+(19/10)*(0)*(1)+(1/2)*Math.pow(0,2)+(-21/10)*(2)+(3/2)*(2)*(1)+(1/2)*(2)*(0)+(3/5)*Math.pow(2,2))
Token (JSified): 30*(-3+(3/5)*(1)+(12/5)*Math.pow(1,2)+4*(0)+(-9/5)*(0)*(1)+-1*Math.pow(0,2)+(6/5)*(2)+(-6/5)*Math.pow(2,2))
Token (JSified): 30*((2/5)*(1)+(-2/5)*Math.pow(1,2)+(-1/5)*(0)*(1)+(4/5)*(2)+1*(2)*(1)+(-4/5)*Math.pow(2,2))
Token (JSified): 30*(1+(-8/5)*(1)+(3/5)*Math.pow(1,2)+(-3/2)*(0)+(3/10)*(0)*(1)+(1/2)*Math.pow(0,2)+(-1/30)*(2)+(-1/2)*(2)*(1)+(-1/2)*(2)*(0)+(8/15)*Math.pow(2,2))
Token (JSified): 30*((-3/5)*(1)+(3/5)*Math.pow(1,2)+(-1/5)*(0)*(1)+(2/15)*(2)+(-2/15)*Math.pow(2,2))
Token (JSified): 30*((7/10)*(1)+(-7/10)*Math.pow(1,2)+(2/5)*(0)*(1)+(-1/10)*(2)+(1/10)*Math.pow(2,2))
Token (JSified): 30*((3/5)*(0)+(-3/5)*Math.pow(0,2)+(1/5)*(0)*(0)+(-3/10)*(2)+(3/10)*Math.pow(2,2))
Token (JSified): 30*((-1/5)*(0)+(6/5)*Math.pow(0,2)+(-2/5)*(0)*(0)+(-2/5)*(2)+-1*(2)*(0)+(2/5)*Math.pow(2,2))
Token (JSified): 30*((-12/5)*(0)+(12/5)*Math.pow(0,2)+(-3/10)*(0)*(0)+(6/5)*(2)+(-3/2)*(2)*(0)+(-1/2)*(2)*(0)+(3/10)*Math.pow(2,2))
Token (JSified): 30*((13/10)*(0)+(-13/10)*Math.pow(0,2)+(1/10)*(0)*(0)+(-2/5)*(2)+(1/2)*(2)*(0)+(1/2)*(2)*(0)+(-1/10)*Math.pow(2,2))
Token (JSified): 30*(3+(6/5)*(0)+(-21/5)*Math.pow(0,2)+(-5/2)*(0)+(19/10)*(0)*(0)+(1/2)*Math.pow(0,2)+(-21/10)*(2)+(3/2)*(2)*(0)+(1/2)*(2)*(0)+(3/5)*Math.pow(2,2))
Token (JSified): 30*(-3+(3/5)*(0)+(12/5)*Math.pow(0,2)+4*(0)+(-9/5)*(0)*(0)+-1*Math.pow(0,2)+(6/5)*(2)+(-6/5)*Math.pow(2,2))
Token (JSified): 30*((2/5)*(0)+(-2/5)*Math.pow(0,2)+(-1/5)*(0)*(0)+(4/5)*(2)+1*(2)*(0)+(-4/5)*Math.pow(2,2))
Token (JSified): 30*(1+(-8/5)*(0)+(3/5)*Math.pow(0,2)+(-3/2)*(0)+(3/10)*(0)*(0)+(1/2)*Math.pow(0,2)+(-1/30)*(2)+(-1/2)*(2)*(0)+(-1/2)*(2)*(0)+(8/15)*Math.pow(2,2))
Token (JSified): 30*((-3/5)*(0)+(3/5)*Math.pow(0,2)+(-1/5)*(0)*(0)+(2/15)*(2)+(-2/15)*Math.pow(2,2))
Token (JSified): 30*((7/10)*(0)+(-7/10)*Math.pow(0,2)+(2/5)*(0)*(0)+(-1/10)*(2)+(1/10)*Math.pow(2,2))
Token (JSified): 30*((3/5)*(0)+(-3/5)*Math.pow(0,2)+(1/5)*(0)*(0)+(-3/10)*(2)+(3/10)*Math.pow(2,2))
Token (JSified): 30*((-1/5)*(0)+(6/5)*Math.pow(0,2)+(-2/5)*(0)*(0)+(-2/5)*(2)+-1*(2)*(0)+(2/5)*Math.pow(2,2))
Token (JSified): 30*((-12/5)*(0)+(12/5)*Math.pow(0,2)+(-3/10)*(0)*(0)+(6/5)*(2)+(-3/2)*(2)*(0)+(-1/2)*(2)*(0)+(3/10)*Math.pow(2,2))
Token (JSified): 30*((13/10)*(0)+(-13/10)*Math.pow(0,2)+(1/10)*(0)*(0)+(-2/5)*(2)+(1/2)*(2)*(0)+(1/2)*(2)*(0)+(-1/10)*Math.pow(2,2))
Token (JSified): 30*(3+(6/5)*(0)+(-21/5)*Math.pow(0,2)+(-5/2)*(0)+(19/10)*(0)*(0)+(1/2)*Math.pow(0,2)+(-21/10)*(2)+(3/2)*(2)*(0)+(1/2)*(2)*(0)+(3/5)*Math.pow(2,2))
Token (JSified): 30*(-3+(3/5)*(0)+(12/5)*Math.pow(0,2)+4*(0)+(-9/5)*(0)*(0)+-1*Math.pow(0,2)+(6/5)*(2)+(-6/5)*Math.pow(2,2))
Token (JSified): 30*((2/5)*(0)+(-2/5)*Math.pow(0,2)+(-1/5)*(0)*(0)+(4/5)*(2)+1*(2)*(0)+(-4/5)*Math.pow(2,2))
Token (JSified): 30*(1+(-8/5)*(0)+(3/5)*Math.pow(0,2)+(-3/2)*(0)+(3/10)*(0)*(0)+(1/2)*Math.pow(0,2)+(-1/30)*(2)+(-1/2)*(2)*(0)+(-1/2)*(2)*(0)+(8/15)*Math.pow(2,2))
Token (JSified): 30*((-3/5)*(0)+(3/5)*Math.pow(0,2)+(-1/5)*(0)*(0)+(2/15)*(2)+(-2/15)*Math.pow(2,2))
Token (JSified): 30*((7/10)*(0)+(-7/10)*Math.pow(0,2)+(2/5)*(0)*(0)+(-1/10)*(2)+(1/10)*Math.pow(2,2))
EXPR (after): 4*(I_1_*(18)+I_2_*(-6)+I_3_*(18)+I_4_*(-6)+I_5_*(36)+I_6_*(-72)+I_7_*(12)+I_8_*(32)+I_9_*(-8)+I_10_*(6))<=(I_1_*(18)+I_2_*(24)+I_3_*(108)+I_4_*(-36)+I_5_*(36)+I_6_*(-162)+I_7_*(-48)+I_8_*(92)+I_9_*(-8)+I_10_*(6))+3*(I_1_*(18)+I_2_*(24)+I_3_*(108)+I_4_*(-36)+I_5_*(36)+I_6_*(-162)+I_7_*(-48)+I_8_*(92)+I_9_*(-8)+I_10_*(6))

Rule: 1<=0
EXPR (before): 1<=0
EXPR (sub-exp removed): 1<=0
EXPR (fraction power removed): 1<=0
LCM: 1
EXPR (after): 1<=0

Rule: I[2,0,1]<=(2)
EXPR (before): (I_1_*((3/5)*((1))+(-3/5)*((1))**2+(1/5)*((0))*((1))+(-3/10)*((2))+(3/10)*((2))**2)+I_2_*((-1/5)*((1))+(6/5)*((1))**2+(-2/5)*((0))*((1))+(-2/5)*((2))+(-1)*((2))*((1))+(2/5)*((2))**2)+I_3_*((-12/5)*((1))+(12/5)*((1))**2+(-3/10)*((0))*((1))+(6/5)*((2))+(-3/2)*((2))*((1))+(-1/2)*((2))*((0))+(3/10)*((2))**2)+I_4_*((13/10)*((1))+(-13/10)*((1))**2+(1/10)*((0))*((1))+(-2/5)*((2))+(1/2)*((2))*((1))+(1/2)*((2))*((0))+(-1/10)*((2))**2)+I_5_*((3)+(6/5)*((1))+(-21/5)*((1))**2+(-5/2)*((0))+(19/10)*((0))*((1))+(1/2)*((0))**2+(-21/10)*((2))+(3/2)*((2))*((1))+(1/2)*((2))*((0))+(3/5)*((2))**2)+I_6_*((-3)+(3/5)*((1))+(12/5)*((1))**2+(4)*((0))+(-9/5)*((0))*((1))+(-1)*((0))**2+(6/5)*((2))+(-6/5)*((2))**2)+I_7_*((2/5)*((1))+(-2/5)*((1))**2+(-1/5)*((0))*((1))+(4/5)*((2))+(1)*((2))*((1))+(-4/5)*((2))**2)+I_8_*((1)+(-8/5)*((1))+(3/5)*((1))**2+(-3/2)*((0))+(3/10)*((0))*((1))+(1/2)*((0))**2+(-1/30)*((2))+(-1/2)*((2))*((1))+(-1/2)*((2))*((0))+(8/15)*((2))**2)+I_9_*((-3/5)*((1))+(3/5)*((1))**2+(-1/5)*((0))*((1))+(2/15)*((2))+(-2/15)*((2))**2)+I_10_*((7/10)*((1))+(-7/10)*((1))**2+(2/5)*((0))*((1))+(-1/10)*((2))+(1/10)*((2))**2))<=(2)
EXPR (sub-exp removed): (I_1_*((3/5)*(1)+(-3/5)*(1)**2+(1/5)*(0)*(1)+(-3/10)*(2)+(3/10)*(2)**2)+I_2_*((-1/5)*(1)+(6/5)*(1)**2+(-2/5)*(0)*(1)+(-2/5)*(2)+-1*(2)*(1)+(2/5)*(2)**2)+I_3_*((-12/5)*(1)+(12/5)*(1)**2+(-3/10)*(0)*(1)+(6/5)*(2)+(-3/2)*(2)*(1)+(-1/2)*(2)*(0)+(3/10)*(2)**2)+I_4_*((13/10)*(1)+(-13/10)*(1)**2+(1/10)*(0)*(1)+(-2/5)*(2)+(1/2)*(2)*(1)+(1/2)*(2)*(0)+(-1/10)*(2)**2)+I_5_*(3+(6/5)*(1)+(-21/5)*(1)**2+(-5/2)*(0)+(19/10)*(0)*(1)+(1/2)*(0)**2+(-21/10)*(2)+(3/2)*(2)*(1)+(1/2)*(2)*(0)+(3/5)*(2)**2)+I_6_*(-3+(3/5)*(1)+(12/5)*(1)**2+4*(0)+(-9/5)*(0)*(1)+-1*(0)**2+(6/5)*(2)+(-6/5)*(2)**2)+I_7_*((2/5)*(1)+(-2/5)*(1)**2+(-1/5)*(0)*(1)+(4/5)*(2)+1*(2)*(1)+(-4/5)*(2)**2)+I_8_*(1+(-8/5)*(1)+(3/5)*(1)**2+(-3/2)*(0)+(3/10)*(0)*(1)+(1/2)*(0)**2+(-1/30)*(2)+(-1/2)*(2)*(1)+(-1/2)*(2)*(0)+(8/15)*(2)**2)+I_9_*((-3/5)*(1)+(3/5)*(1)**2+(-1/5)*(0)*(1)+(2/15)*(2)+(-2/15)*(2)**2)+I_10_*((7/10)*(1)+(-7/10)*(1)**2+(2/5)*(0)*(1)+(-1/10)*(2)+(1/10)*(2)**2))<=2
EXPR (fraction power removed): (I_1_*((3/5)*(1)+(-3/5)*(1)**2+(1/5)*(0)*(1)+(-3/10)*(2)+(3/10)*(2)**2)+I_2_*((-1/5)*(1)+(6/5)*(1)**2+(-2/5)*(0)*(1)+(-2/5)*(2)+-1*(2)*(1)+(2/5)*(2)**2)+I_3_*((-12/5)*(1)+(12/5)*(1)**2+(-3/10)*(0)*(1)+(6/5)*(2)+(-3/2)*(2)*(1)+(-1/2)*(2)*(0)+(3/10)*(2)**2)+I_4_*((13/10)*(1)+(-13/10)*(1)**2+(1/10)*(0)*(1)+(-2/5)*(2)+(1/2)*(2)*(1)+(1/2)*(2)*(0)+(-1/10)*(2)**2)+I_5_*(3+(6/5)*(1)+(-21/5)*(1)**2+(-5/2)*(0)+(19/10)*(0)*(1)+(1/2)*(0)**2+(-21/10)*(2)+(3/2)*(2)*(1)+(1/2)*(2)*(0)+(3/5)*(2)**2)+I_6_*(-3+(3/5)*(1)+(12/5)*(1)**2+4*(0)+(-9/5)*(0)*(1)+-1*(0)**2+(6/5)*(2)+(-6/5)*(2)**2)+I_7_*((2/5)*(1)+(-2/5)*(1)**2+(-1/5)*(0)*(1)+(4/5)*(2)+1*(2)*(1)+(-4/5)*(2)**2)+I_8_*(1+(-8/5)*(1)+(3/5)*(1)**2+(-3/2)*(0)+(3/10)*(0)*(1)+(1/2)*(0)**2+(-1/30)*(2)+(-1/2)*(2)*(1)+(-1/2)*(2)*(0)+(8/15)*(2)**2)+I_9_*((-3/5)*(1)+(3/5)*(1)**2+(-1/5)*(0)*(1)+(2/15)*(2)+(-2/15)*(2)**2)+I_10_*((7/10)*(1)+(-7/10)*(1)**2+(2/5)*(0)*(1)+(-1/10)*(2)+(1/10)*(2)**2))<=2
LCM: 30
Token (JSified): 30*((3/5)*(1)+(-3/5)*Math.pow(1,2)+(1/5)*(0)*(1)+(-3/10)*(2)+(3/10)*Math.pow(2,2))
Token (JSified): 30*((-1/5)*(1)+(6/5)*Math.pow(1,2)+(-2/5)*(0)*(1)+(-2/5)*(2)+-1*(2)*(1)+(2/5)*Math.pow(2,2))
Token (JSified): 30*((-12/5)*(1)+(12/5)*Math.pow(1,2)+(-3/10)*(0)*(1)+(6/5)*(2)+(-3/2)*(2)*(1)+(-1/2)*(2)*(0)+(3/10)*Math.pow(2,2))
Token (JSified): 30*((13/10)*(1)+(-13/10)*Math.pow(1,2)+(1/10)*(0)*(1)+(-2/5)*(2)+(1/2)*(2)*(1)+(1/2)*(2)*(0)+(-1/10)*Math.pow(2,2))
Token (JSified): 30*(3+(6/5)*(1)+(-21/5)*Math.pow(1,2)+(-5/2)*(0)+(19/10)*(0)*(1)+(1/2)*Math.pow(0,2)+(-21/10)*(2)+(3/2)*(2)*(1)+(1/2)*(2)*(0)+(3/5)*Math.pow(2,2))
Token (JSified): 30*(-3+(3/5)*(1)+(12/5)*Math.pow(1,2)+4*(0)+(-9/5)*(0)*(1)+-1*Math.pow(0,2)+(6/5)*(2)+(-6/5)*Math.pow(2,2))
Token (JSified): 30*((2/5)*(1)+(-2/5)*Math.pow(1,2)+(-1/5)*(0)*(1)+(4/5)*(2)+1*(2)*(1)+(-4/5)*Math.pow(2,2))
Token (JSified): 30*(1+(-8/5)*(1)+(3/5)*Math.pow(1,2)+(-3/2)*(0)+(3/10)*(0)*(1)+(1/2)*Math.pow(0,2)+(-1/30)*(2)+(-1/2)*(2)*(1)+(-1/2)*(2)*(0)+(8/15)*Math.pow(2,2))
Token (JSified): 30*((-3/5)*(1)+(3/5)*Math.pow(1,2)+(-1/5)*(0)*(1)+(2/15)*(2)+(-2/15)*Math.pow(2,2))
Token (JSified): 30*((7/10)*(1)+(-7/10)*Math.pow(1,2)+(2/5)*(0)*(1)+(-1/10)*(2)+(1/10)*Math.pow(2,2))
Scalar: 30*(2)
EXPR (after): (I_1_*(18)+I_2_*(-6)+I_3_*(18)+I_4_*(-6)+I_5_*(36)+I_6_*(-72)+I_7_*(12)+I_8_*(32)+I_9_*(-8)+I_10_*(6))<=60

Point (2 0 1) failed
New constraint:
s.add(And(0<=(I_1_*(18)+I_2_*(-6)+I_3_*(18)+I_4_*(-6)+I_5_*(36)+I_6_*(-72)+I_7_*(12)+I_8_*(32)+I_9_*(-8)+I_10_*(6)), Implies(1>0, 4*(I_1_*(18)+I_2_*(-6)+I_3_*(18)+I_4_*(-6)+I_5_*(36)+I_6_*(-72)+I_7_*(12)+I_8_*(32)+I_9_*(-8)+I_10_*(6))<=(I_1_*(18)+I_2_*(24)+I_3_*(108)+I_4_*(-36)+I_5_*(36)+I_6_*(-162)+I_7_*(-48)+I_8_*(92)+I_9_*(-8)+I_10_*(6))+3*(I_1_*(18)+I_2_*(24)+I_3_*(108)+I_4_*(-36)+I_5_*(36)+I_6_*(-162)+I_7_*(-48)+I_8_*(92)+I_9_*(-8)+I_10_*(6))), Implies(1<=0, (I_1_*(18)+I_2_*(-6)+I_3_*(18)+I_4_*(-6)+I_5_*(36)+I_6_*(-72)+I_7_*(12)+I_8_*(32)+I_9_*(-8)+I_10_*(6))<=60)))
Z3 Error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/z3/z3.py", line 7029, in model
    return ModelRef(Z3_solver_get_model(self.ctx.ref(), self.solver), self.ctx)
  File "/usr/local/lib/python3.8/site-packages/z3/z3core.py", line 3833, in Z3_solver_get_model
    _elems.Check(a0)
  File "/usr/local/lib/python3.8/site-packages/z3/z3core.py", line 1416, in Check
    raise self.Exception(self.get_error_message(ctx, err))
z3.z3types.Z3Exception: b'there is no current model'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 35, in <module>
  File "/usr/local/lib/python3.8/site-packages/z3/z3.py", line 7031, in model
    raise Z3Exception("model is not available")
z3.z3types.Z3Exception: model is not available

Invariant does not exists.

RedLog rules:   ((0.25*n*y)<=I[x,y,n]) and ((n>0) impl (4*I[x,y,n]<=I[x+y,y,n-1]+3*I[x,y,n-1])) and ((n<=0) impl (I[x,y,n]<=(x)))

Profiling of binomial
Building sample space:  0.01s
Computing basis:        0.59s
Guessing coefficients:  4.14s
Random tests:   16.74s
Total execution time:   21.51s
No. of basis searchs:   2
No. of refinements:     9
No. of random tests:    46
Pre-expectation:        0.25*n*y
Post-expectation:       x
Invariant:              None

**Comment by ericpony** [comment]
Thanks for the report. The script did produce an invariant for the binomial test case last time I run it. According to your log, the script generated a malformed z3py constraint (following the "New constraint:" line), and Z3 expectedly failed to produce a new condidate invariant from this constraint. I am not sure why the contraint would be malformed in your execution --- a possible reason is that the versions of z3py and Redlog you used behave differently from those I used 7 years ago.

I have tried to run the script myself after seeing this report. Unfortunately, I could not build a working environment for the script after hours of work. If you would like me to debug this issue soon, could you please do me a favor and build a minimal working environment for me? You can create a virtual machine in VDI format, upload it to somewhere, and mail the link to me. Thanks a lot.

**Comment by ericpony** [comment]
Thanks for the report. The script did produce an invariant for the binomial test case last time I ran it. According to your log, the script generated a malformed z3py constraint (following the "New constraint:" line), and expectedly, Z3 failed to produce a new candidate invariant from this constraint. I am not sure why the constraint would be malformed in your execution --- a possible reason is that the versions of z3py and Redlog you used behave differently from those I used 7 years ago.

I have tried to run the script myself after seeing this report. Unfortunately, I could not build a working environment for the script after hours of work. If you would like me to debug this issue soon, could you please do me a favor and build a minimal working environment for me? You can create a virtual machine in VDI format, upload it to somewhere in the cloud, and mail the link to me. Thanks a lot.

**Comment by ericpony** [comment]
Thanks for the report. The script did produce an invariant for the binomial test case last time I ran it. According to your log, the script generated a malformed z3py constraint (following the "New constraint:" line), and expectedly, Z3 failed to produce a new candidate invariant from this constraint. I am not sure why the constraint would be malformed in your execution --- a possible reason is that the versions of z3py and Redlog you used behave differently from those I used 7 years ago.

I have tried to run the script myself after seeing this report. Unfortunately, I could not build a working environment for the script after hours of efforts. If you would like me to debug this issue soon, could you please do me a favor and build a minimal working environment for me? You can create a virtual machine in VDI format, upload it to somewhere in the cloud, and mail the link to me. Thanks a lot.

**Comment by trivedi-nitesh** [comment]
Thankyou for your quick response. You can use my docker image uploaded on my docker hub account. You can simply pull the image using "docker pull nitesht/lagrange:v2". You might need to change print statements in main.js file as docker image contains python 3.8. Feel free to contact if you face any difficulty in setting up the environment with docker.
